name: Benchmark Zig Proxy vs Nginx

on:
  push:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx wrk bc

          # Configure Nginx to serve from our public folder
          sudo cp -r public/* /var/www/html/
          sudo systemctl restart nginx

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.13

      - name: Build Zig proxy
        run: |
          zig build -Doptimize=ReleaseFast

      - name: Start Zig proxy
        run: |
          ./zig-out/bin/zig_http_server & echo $! > zig_proxy.pid
          sleep 2  # Wait for it to be ready

      - name: Benchmark Zig proxy
        run: |
          wrk -t4 -c50 -d10s http://localhost:8080 > zig_bench.txt

      - name: Benchmark Nginx
        run: |
          wrk -t4 -c50 -d10s http://localhost/index.html > nginx_bench.txt

      - name: Compare results
        run: |
          echo "Zig Proxy Benchmark (serving from public folder):"
          cat zig_bench.txt
          echo "-----------------------------------------"
          echo "Nginx Benchmark (serving from same public folder):"
          cat nginx_bench.txt
          echo "-----------------------------------------"
          echo "Comparing request throughput:"
          ZIG_RPS=$(grep "Requests/sec" zig_bench.txt | awk '{print $2}')
          NGINX_RPS=$(grep "Requests/sec" nginx_bench.txt | awk '{print $2}')
          echo "Zig: $ZIG_RPS requests/sec"
          echo "Nginx: $NGINX_RPS requests/sec"

          if (( $(echo "$ZIG_RPS > $NGINX_RPS" | bc -l) )); then
            PERC_DIFF=$(echo "scale=2; ($ZIG_RPS - $NGINX_RPS) * 100 / $NGINX_RPS" | bc)
            echo "Zig is $PERC_DIFF% faster than Nginx"
          else
            PERC_DIFF=$(echo "scale=2; ($NGINX_RPS - $ZIG_RPS) * 100 / $ZIG_RPS" | bc)
            echo "Nginx is $PERC_DIFF% faster than Zig"
          fi

      - name: Stop Zig proxy
        run: |
          kill $(cat zig_proxy.pid) || true

      - name: Upload results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: benchmark-results
          path: |
            zig_bench.txt
            nginx_bench.txt
